server:
  port: 8086

spring:
  application:
    name: shipments
  datasource:
    url: jdbc:postgresql://localhost:5432/fedb
    username: postgres
    password: 622000
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: "configserver:http://localhost:8071/"